version: '3'
services:

  api:
    build: ./services/api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./services/api/:/myapp
    ports:
      - "3000:3000"
    env_file:
      - ./services/api/development.env
    depends_on:
      - api_redis
      - dictionary_redis


  api_redis:
    image: redis
    volumes:
      - 'redis:/data'
    expose:
      - 6379


  dictionary_redis:
    build: ./services/dictionary
    expose:
      - 6379

  react:
    build: ./services/react
    volumes:
      - './services/react/:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true


volumes:
  redis: